
services:
  serv:
    build: ./src
    ports:
      - ${SERV_PORT}:5000
  db:
    image: postgres:15.6
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: tictacpostgres
    ports:
      - ${POSTGRES_PORT}:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - ${ADMIN_PORT}:8080
      
  front:
    build: ${FRONT_PATH}
    ports:
      - ${FRONT_PORT}:3000